// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyejpbjdhunrnogirvjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5ZWpwYmpkaHVucm5vZ2lydmpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MTM1NDksImV4cCI6MjA2NDE4OTU0OX0.XPgg5n_cj21tlj_I5OlBrl48LT5Ly4sKg_e9A8RmeJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);